{{- if .Values.garage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackweaver.fullname" . }}-garage
  labels:
    {{- include "stackweaver.labels" . | nindent 4 }}
    app.kubernetes.io/component: garage
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: 3900
      targetPort: s3
    - name: admin
      port: 3903
      targetPort: admin
  selector:
    {{- include "stackweaver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: garage
{{- end }}
