{{- if .Values.zitadel.bundled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stackweaver.fullname" . }}-zitadel-pat
  labels:
    {{- include "stackweaver.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
{{- end }}
